[tool.poetry]
name = "smart-audio"
version = "0.1.0"
description = ""
authors = ["max-benzait <max.ramirez@benzait.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pyaudio = "^0.2.14"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
